Adding security mitigation files to artifactory charts
jfrog/charts pull request #1116
Opened 2020-09-21 12:17 UTC by shahiinn

#### PR Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.]
- [ ] Chart Version bumped
- [ ] CHANGELOG.md updated
- [ ] Variables and other changes are documented in the README.md
- [ ] Title of the PR starts with chart name (e.g. `[artifactory]`)

**What this PR does / why we need it**:

**Which issue this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close that issue when PR gets merged)*: fixes #

**Special notes for your reviewer**:

2020-09-21 13:25 UTC, eldada reviewed
Few comments:
1. Need to bump chart versions + changelog entry
2. The oss, jcr and cpp charts use the artifactory as a sub-chart. Do we still have to add this file to them as this is coming from a dependency
3. Add new line to the end of the files please

2020-09-21 13:47 UTC, rimusz commented
> Few comments:
> 
> 1. Need to bump chart versions + changelog entry
> 2. The oss, jcr and cpp charts use the artifactory as a sub-chart. Do we still have to add this file to them as this is coming from a dependency
> 3. Add new line to the end of the files please

2. No need to add security mitigation file for sub-charts

2020-09-21 18:23 UTC, rimusz requested changes

2020-09-21 18:23 UTC, rimusz commented on stable/artifactory-ha/security-mitigation.yaml
>    affectedVersions: < 10.0.0
wrong chart version

2020-09-21 19:08 UTC, rimusz approved these changes

2020-09-21 19:28 UTC, eldada approved these changes

2020-09-22 03:52 UTC, rahulsadanandan approved these changes

2020-09-22 05:19 UTC, chukka approved these changes

2020-09-22 10:43 UTC, merged